In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rabieelkharoua/predict-conversion-in-digital-marketing-dataset/digital_marketing_campaign_dataset.csv

In [2]:
import pandas as pd
df = pd.read_csv('/kaggle/input/datasets/rabieelkharoua/predict-conversion-in-digital-marketing-dataset/digital_marketing_campaign_dataset.csv')
df.head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,2.399017,7.396803,19,6,9,4,688,IsConfid,ToolConfid,1
1,8001,69,Male,41760,Email,Retention,3898.668606,0.155725,0.182725,42,2.917138,5.352549,5,2,7,2,3459,IsConfid,ToolConfid,1
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,8.223619,13.794901,0,11,2,8,2337,IsConfid,ToolConfid,1
3,8003,32,Female,44085,PPC,Conversion,539.525936,0.137611,0.088004,47,4.540939,14.688363,89,2,2,0,2463,IsConfid,ToolConfid,1
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,2.046847,13.993370,6,6,6,8,4345,IsConfid,ToolConfid,1

In [3]:
df.describe()

,CustomerID,Age,Income,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,PagesPerVisit,TimeOnSite,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,Conversion
count,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,11999.50000,43.625500,84664.196750,5000.944830,0.154829,0.104389,24.751625,5.549299,7.727718,49.799750,9.476875,4.467375,4.485500,2490.268500,0.876500
std,2309.54541,14.902785,37580.387945,2838.038153,0.084007,0.054878,14.312269,2.607358,4.228218,28.901165,5.711111,2.856564,2.888093,1429.527162,0.329031
min,8000.00000,18.000000,20014.000000,100.054813,0.010005,0.010018,0.000000,1.000428,0.501669,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9999.75000,31.000000,51744.500000,2523.221165,0.082635,0.056410,13.000000,3.302479,4.068340,25.000000,5.000000,2.000000,2.000000,1254.750000,1.000000
50%,11999.50000,43.000000,84926.500000,5013.440044,0.154505,0.104046,25.000000,5.534257,7.682956,50.000000,9.000000,4.000000,4.000000,2497.000000,1.000000
75%,13999.25000,56.000000,116815.750000,7407.989369,0.228207,0.152077,37.000000,7.835756,11.481468,75.000000,14.000000,7.000000,7.000000,3702.250000,1.000000
max,15999.00000,69.000000,149986.000000,9997.914781,0.299968,0.199995,49.000000,9.999055,14.995311,99.000000,19.000000,9.000000,9.000000,4999.000000,1.000000

## Customer Engagement Variables

The Following Variables were selected because they represent customer engagement and purchasing behavior:

- EmailOpens
- EmailClicks
- WebsiteVisits
- PagesPerVisits
- TimeOnSite
- LoyaltyPoints
- PreviousPurchases

These variables will be used to identify customer segments.

In [4]:
engagement_columns = [
    'EmailOpens',
    'EmailClicks',
    'WebsiteVisits',
    'PagesPerVisit',
    'TimeOnSite',
    'LoyaltyPoints',
    'PreviousPurchases'
    
]

df[engagement_columns].describe()

,EmailOpens,EmailClicks,WebsiteVisits,PagesPerVisit,TimeOnSite,LoyaltyPoints,PreviousPurchases
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,9.476875,4.467375,24.751625,5.549299,7.727718,2490.268500,4.485500
std,5.711111,2.856564,14.312269,2.607358,4.228218,1429.527162,2.888093
min,0.000000,0.000000,0.000000,1.000428,0.501669,0.000000,0.000000
25%,5.000000,2.000000,13.000000,3.302479,4.068340,1254.750000,2.000000
50%,9.000000,4.000000,25.000000,5.534257,7.682956,2497.000000,4.000000
75%,14.000000,7.000000,37.000000,7.835756,11.481468,3702.250000,7.000000
max,19.000000,9.000000,49.000000,9.999055,14.995311,4999.000000,9.000000

In [5]:
df['EngagementScore'] = (
    df['EmailOpens'] +
    df['EmailClicks'] +
    df ['WebsiteVisits'] +
    df['PagesPerVisit'] +
    df['TimeOnSite']
)

df['EngagementScore'].describe()

count    8000.000000
mean       51.972892
std        16.375366
min         7.491488
25%        39.420624
50%        51.888127
75%        64.664686
max        98.047884
Name: EngagementScore, dtype: float64

In [6]:
df['EngagementSegment'] = pd.qcut (
    df['EngagementScore'],
    q=3,
    labels=[
    'Low Engagement',
    'Medium Engagement',
    'High Engagement'
    ]
)
df['EngagementSegment'].value_counts()

EngagementSegment
Low Engagement       2667
High Engagement      2667
Medium Engagement    2666
Name: count, dtype: int64

In [7]:
df.groupby('EngagementSegment')['Conversion'].mean()

/tmp/ipykernel_16/1714490303.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('EngagementSegment')['Conversion'].mean()

EngagementSegment
Low Engagement       0.808024
Medium Engagement    0.899100
High Engagement      0.922385
Name: Conversion, dtype: float64

In [8]:
df.groupby('EngagementSegment')[[
    'EmailOpens',
    'EmailClicks',
    'WebsiteVisits',
    'PagesPerVisit',
    'TimeOnSite'
]].mean()

/tmp/ipykernel_16/173230418.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('EngagementSegment')[[

,EmailOpens,EmailClicks,WebsiteVisits,PagesPerVisit,TimeOnSite
EngagementSegment,,,,,
Low Engagement,7.471316,3.974128,10.182977,5.177007,6.732589
Medium Engagement,9.442236,4.508252,24.806827,5.525430,7.742391
High Engagement,11.517060,4.919760,39.265092,5.945452,8.708180

### Low engagement Segment

- Customers: 2,667
- Conversion Rate: 80.8%
- Lowest email interaction
- Lowest website activity

Business risk:

These customers are less engaged with marketing content and have the lowest conversion performance.

Recommended Action:

Launch re-engagement campaigns to increase interaction and conversion potential.

In [9]:
low_engagement = df[
df['EngagementSegment'] == 'Low Engagement'
]
low_engagement.head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,...,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion,EngagementScore,EngagementSegment
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,...,19,6,9,4,688,IsConfid,ToolConfid,1,24.795819,Low Engagement
2,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,...,0,11,2,8,2337,IsConfid,ToolConfid,1,37.018521,Low Engagement
4,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,...,6,6,6,8,4345,IsConfid,ToolConfid,1,28.040218,Low Engagement
5,8005,25,Female,42925,Social Media,Awareness,9579.388247,0.153795,0.161316,6,...,95,5,8,0,3316,IsConfid,ToolConfid,1,28.878681,Low Engagement
9,8009,40,Male,130764,Social Media,Awareness,6229.193333,0.066641,0.169786,22,...,14,8,4,8,3789,IsConfid,ToolConfid,1,39.748977,Low Engagement

In [10]:
low_engagement.to_csv(
    'low_engagement_customers.csv',
    index=False
)

# Key Findings

- Customers were segmented into Low, Medium, and High Engagement Groups.
- High Engagement customers achieved the highest conversion rate (92.2%).
- Medium engagement customers achieved a conversion rate of 89.9%
- Low Engagement customers achieved the lowest conversion rate (80.8%)
- Higher engagement levels were associated with higher conversion rates.

# Recommendations

- Prioritize conversion campaigns for High Engagement customers.
- Develop personalized campaigns for Medium Engagement customers.
- Create re-engagement initiatives for low-engagement customers.
- Focus on increasing email interaction and website engagement.

# Conclusion

The analysis identified a clear relationship between customer engagement and conversion performance.

Cusotmers with higher engagement levels consistently achieved higher engagement levels consistently achieved higher conversion rates. These findings support the use of engagement-based segmentation to improve marketing effectiveness and customer retention.

In [11]:
import os 
os.listdir()

['__notebook__.ipynb', 'low_engagement_customers.csv']

In [12]:
pd.read_csv('low_engagement_customers.csv').head()

,CustomerID,Age,Gender,Income,CampaignChannel,CampaignType,AdSpend,ClickThroughRate,ConversionRate,WebsiteVisits,...,SocialShares,EmailOpens,EmailClicks,PreviousPurchases,LoyaltyPoints,AdvertisingPlatform,AdvertisingTool,Conversion,EngagementScore,EngagementSegment
0,8000,56,Female,136912,Social Media,Awareness,6497.870068,0.043919,0.088031,0,...,19,6,9,4,688,IsConfid,ToolConfid,1,24.795819,Low Engagement
1,8002,46,Female,88456,PPC,Awareness,1546.429596,0.277490,0.076423,2,...,0,11,2,8,2337,IsConfid,ToolConfid,1,37.018521,Low Engagement
2,8004,60,Female,83964,PPC,Conversion,1678.043573,0.252851,0.109940,0,...,6,6,6,8,4345,IsConfid,ToolConfid,1,28.040218,Low Engagement
3,8005,25,Female,42925,Social Media,Awareness,9579.388247,0.153795,0.161316,6,...,95,5,8,0,3316,IsConfid,ToolConfid,1,28.878681,Low Engagement
4,8009,40,Male,130764,Social Media,Awareness,6229.193333,0.066641,0.169786,22,...,14,8,4,8,3789,IsConfid,ToolConfid,1,39.748977,Low Engagement

In [13]:
df.to_csv(
    'customer_segmentation_results',
    index=False
)

In [14]:
import os 
os.listdir()

['__notebook__.ipynb',
 'low_engagement_customers.csv',
 'customer_segmentation_results']